### PR TITLE
Fix the Home button that hasn't been fixed in 4 years

### PR DESCRIPTION
**Pull request by riko**

### CODE REVIEW

**Comment by r3muxd** [comment]
https://github.com/r3muxd/tunnel-fixer/blob/6a6956f2688026295ada8baf433bab39df4578ae/collabvm.html#L28

mb learn2code before pasting from ur god,, SORRY

**Comment by r3muxd** [comment]
https://github.com/r3muxd/tunnel-fixer/blob/6a6956f2688026295ada8baf433bab39df4578ae/collabvm.html#L28

mb learn2code before pasting from ur god,, SORRY
(improper fix aswell)

**Comment by dr3murr** [comment]
https://github.com/r3muxd/tunnel-fixer/blob/6a6956f2688026295ada8baf433bab39df4578ae/collabvm.html#L28

mb learn2code before pasting from ur god,, SORRY
(improper fix aswell, read orig source before posting again...)

**Comment by qtAmyVT** [comment]
I think if you were gonna use a proper /index.html or a / page i think we shouldn't need `location.reload();`, users can force stop the page from reloading or prevent a page from reloading (there are addons on firefox on my daily browser). I believe it should use /index.html if a server has configured it properly.

**Comment by qtAmyVT** [comment]
Or make a index.html page and then use the Home button redirect to the index.html.

**Comment by yellows111** [comment]
going to recap what i've said from before, I was considering a return/callback function for the home button rather than just refreshing the page, i've thought about implementation and the way I am seeing it, it *can* work better.

**Comment by dr3murr** [comment]
or you could actually fix the fucking button to do what it was meant to do originally and did until someone fucked with it

here's your free hint
```
$("#home-btn").attr("href", rootDir).click(function(e) {
    // Check that the link was clicked with the left mouse button
    if (e.which === 1) {
        e.preventDefault();
        if ($("#vm-list").is(":visible")) {
            getVMList();
        } else {
            History.pushState(null, null, this.getAttribute("href"));
        }
    }
});
```

this block of code broke with a certain update in like 2016
fixing this is an exercise left to the reader because i lost my old hdd with the fix and refuse to rewrite it out of spite (also, `tunnel.sendMessage("connect")` no longer works thanks to server crashing funnies xDDDDDDDDDDDDD)
#FreeSorry

**Comment by dfault-user** [comment]
github pull request comments my beloved

**Comment by dr3murr** [comment]
player_pos + player_velocity / interval_per_tick = my lagfix

**Comment by dfault-user** [comment]
guys, guys, GUYS GUYS GUYS AMONG US HOLY SHIT. AMONG US. LISTEN. HIT GAME. 2018 HAS THIS NEW GAME CALLED AMONG US YOU SHOULD CHECK IT OUT AMONG US AMONG US 
äîèóiuuuaooeoo

**Comment by re9177** [comment]
> #FreeSorry

you still in the prison cell after all these years? when is the next parole coming?

**Comment by dr3murr** [comment]
is gecko prison
i only get parole if i speak fluent chinese

**Comment by qtAmyVT** [comment]
Again, please do not use `location.reload();`, just use or make a index.html page instead.

**Comment by yellows111** [comment]
your're mouth is 
moving alot like a rouse
yappa yappa yappa
shut it please

---

I'm Busy with my life

**Comment by dfault-user** [comment]
among us
among us
among us
among us
among us
among us
among us
among us
among us
among us
among us
among us
among us
among us
among us
among us
among us

Thanks,
Brandan Delafuente
***@***.***

**Comment by qtAmyVT** [comment]
> 
> 
> your're mouth is
> moving alot like a rouse
> yappa yappa yappa
> shut it please
> 
> I'm Busy with my life

Can you fix the home button then just being lazy.

**Comment by nephacks** [comment]
shut and Cope

**Comment by dr3murr** [comment]
1633403037h4tLaSRSMGY

**Comment by dfault-user** [comment]
im in school please stop posting cats
Thanks,
Brandan Delafuente
***@***.***

**Pull request closed without merging**
